#!/usr/bin/env python3
"""Interactive configuration setup wizard for Apartment Hunter."""

import os
from pathlib import Path

def get_input(prompt, default=""):
    val = input(f"{prompt} [{default}]: ").strip()
    return val if val else default

def get_bool_input(prompt, default="no"):
    while True:
        val = input(f"{prompt} (yes/no) [{default}]: ").strip().lower()
        if not val:
            val = default
        if val in {"y", "yes", "true", "1"}:
            return "true"
        if val in {"n", "no", "false", "0"}:
            return "false"
        print("Please enter 'yes' or 'no'.")

def main():
    print("=========================================")
    print("       🏠 Apartment Hunter Setup Wizard  ")
    print("=========================================\n")
    print("This setup will guide you through creating your .env configuration file.\n")

    env_path = Path(".env")
    current_config = {}

    # Read existing config if present
    if env_path.exists():
        print("Found existing .env file. Using its values as defaults...\n")
        with open(env_path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    parts = line.split("=", 1)
                    if len(parts) == 2:
                        k, v = parts
                        current_config[k.strip()] = v.strip()

    # Prompts
    city = get_input("Where are you searching for an apartment (City/Locality name)?", current_config.get("TARGET_CITY", "gent"))
    postal_code = get_input("What is the postal code?", current_config.get("TARGET_POSTAL_CODE", "9000"))
    
    while True:
        try:
            min_price = int(get_input("What is your minimum budget (€)?", current_config.get("MIN_PRICE", "800")))
            break
        except ValueError:
            print("Please enter a valid number.")

    while True:
        try:
            max_price = int(get_input("What is your maximum budget (€)?", current_config.get("MAX_PRICE", "1000")))
            break
        except ValueError:
            print("Please enter a valid number.")

    while True:
        try:
            min_bedrooms = int(get_input("What is the minimum number of bedrooms?", current_config.get("MIN_BEDROOMS", "1")))
            break
        except ValueError:
            print("Please enter a valid number.")

    enable_station = get_bool_input("Do you want to enable location-based proximity filtering (e.g. near station)?", current_config.get("ENABLE_STATION_FILTER", "no"))
    
    near_keywords = ""
    far_keywords = ""
    if enable_station == "true":
        near_keywords = get_input(
            "Enter keywords for preferred locations (comma-separated, leave blank for defaults)",
            current_config.get("STATION_NEAR_KEYWORDS", "")
        )
        far_keywords = get_input(
            "Enter keywords for excluded locations (comma-separated, leave blank for defaults)",
            current_config.get("STATION_FAR_KEYWORDS", "")
        )

    # Gmail SMTP config
    gmail_from = get_input("Gmail address to send notifications FROM?", current_config.get("GMAIL_FROM", "your-email@gmail.com"))
    gmail_app_pw = get_input("Gmail App Password (not your main password)?", current_config.get("GMAIL_APP_PASSWORD", "xxxx-xxxx-xxxx-xxxx"))
    email_to = get_input("Email address to send digests TO?", current_config.get("EMAIL_TO", "recipient@example.com"))
    email_cc = get_input("CC email address (optional)?", current_config.get("EMAIL_CC", ""))

    # AI Keys
    groq_key = get_input("Groq API Key (for AI text scoring, optional)?", current_config.get("GROQ_API_KEY", ""))
    openrouter_key = get_input("OpenRouter API Key (for AI photo scoring, optional)?", current_config.get("OPENROUTER_API_KEY", ""))
    enable_photos = get_bool_input("Enable AI photo scoring if OpenRouter key is set?", current_config.get("ENABLE_PHOTO_SCORING", "true"))

    # Construct file content
    env_content = f"""# ==========================================
# 🏠 Apartment Hunter Configuration
# Generated by setup.py
# ==========================================

# Search Criteria
TARGET_CITY={city}
TARGET_POSTAL_CODE={postal_code}
MIN_PRICE={min_price}
MAX_PRICE={max_price}
MIN_BEDROOMS={min_bedrooms}

# Location/Proximity Filtering (Optional)
ENABLE_STATION_FILTER={enable_station}
STATION_NEAR_KEYWORDS={near_keywords}
STATION_FAR_KEYWORDS={far_keywords}

# Email Notifications (Gmail SMTP)
GMAIL_FROM={gmail_from}
GMAIL_APP_PASSWORD={gmail_app_pw}
EMAIL_TO={email_to}
EMAIL_CC={email_cc}

# AI Quality Scoring (Optional)
GROQ_API_KEY={groq_key}
OPENROUTER_API_KEY={openrouter_key}
ENABLE_PHOTO_SCORING={enable_photos}
"""

    with open(env_path, "w", encoding="utf-8") as f:
        f.write(env_content)

    print("\n=========================================")
    print("✅ Configuration saved successfully to .env!")
    print("=========================================\n")

if __name__ == "__main__":
    main()
